front:
  image: cjf-dev
  ports:
    - "8080:80"
  environment:
    XDEBUG_CONFIG: "remote_host=192.168.1.16"
    PHP_IDE_CONFIG: "serverName=alvara"
  volumes:
    - ./:/var/www
    - ./sites:/etc/nginx/sites-enabled

db:
  image: sath89/oracle-xe-11g
  ports:
      - 1521:1521